[build]
    command = "npm run build"
    functions = "out_functions"
    publish = ".next"

[dev]
    functions = "out_functions"
    publish = ".next"
    framework = "#static"

[[plugins]]
    package = "@netlify/plugin-nextjs"
